Repository valueGa/valueGa_frontend, pull requests merged in 2024-06, with the labels that each got.

#5 [CHORE] tailwind config 설정 #4
  index.html
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoEB.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoH.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoL.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoSB.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoT.ttf
  public/assets/font/AppleSDGothicNeo/AppleSDGothicNeoUL.ttf
  src/index.css
  src/routes/main/page.jsx
  tailwind.config.js
Labels: chore

#7 [Feat] 페이지 이동 전체 설정 #6
  src/App.css
  src/App.jsx
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/components/consensus/myPage/MyPage.jsx
  src/components/consensus/valuation/Valuation.jsx
  src/index.css
  src/main.jsx
  src/routers/main-router.jsx
  src/routes/consensus/page.jsx
  src/routes/main/page.jsx
  vite.config.js
Labels: feat

#9 [FIX] tailwind 폰트 크기 축소 #8
  tailwind.config.js
Labels: fix

#12 [FEAT] 템플릿 생성하기 #3
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/consensus/valuation/Excel.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/Valuation.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
  src/routers/main-router.jsx
  src/routes/consensus/page.jsx
  src/routes/valuationCreateExcel/page.jsx
Labels: feat

#17 Feature/#2
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoEB.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoH.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoL.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoSB.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoT.ttf
  dist/assets/font/AppleSDGothicNeo/AppleSDGothicNeoUL.ttf
  dist/assets/index-C1l0lrcq.js
  dist/assets/index-CXuW3aw4.css
  dist/assets/index-DlAwgnMw.js
  dist/assets/index-fNCE5DMw.css
  dist/bg_lines.svg
  dist/ic_chart.svg
  dist/ic_expression.svg
  dist/ic_send.png
  dist/img_3d.svg
  dist/img_arrow_right.svg
  dist/img_chart.svg
  dist/img_demo.svg
  dist/img_demo_2.svg
  dist/index.html
  dist/logo_text.svg
  package-lock.json
  package.json
  public/bg_lines.svg
  public/ic_chart.svg
  public/ic_expression.svg
  public/ic_send.png
  public/img_3d.svg
  public/img_arrow_right.svg
  public/img_chart.svg
  public/img_demo.svg
  public/img_demo_2.svg
  public/logo_text.svg
  src/routes/main/MainFooter.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
  src/routes/main/TabAboutUs.jsx
  src/routes/main/TabContact.jsx
  src/routes/main/TabHome.jsx
  src/routes/main/TabService.jsx
  src/routes/main/page.jsx
Labels: feat

#21 [FEAT] 임시 저장, 저장 버튼 UI 구현
  src/components/consensus/valuation/ExcelFooter.jsx
  src/routes/valuationCreateExcel/page.jsx
Labels: feat

#24 [FEAT] 로그인/회원가입 모달 구현
  package-lock.json
  public/assets/images/bg_lines.svg
  public/assets/images/ic_block.svg
  public/assets/images/ic_chart.svg
  public/assets/images/ic_check.svg
  public/assets/images/ic_close.svg
  public/assets/images/ic_email.svg
  public/assets/images/ic_expression.svg
  public/assets/images/ic_send.png
  public/assets/images/img_3d.svg
  public/assets/images/img_arrow_right.svg
  public/assets/images/img_chart.svg
  public/assets/images/img_demo.svg
  public/assets/images/img_demo_2.svg
  public/assets/images/logo_text.svg
  public/assets/images/vite.svg
  src/components/consensus/home/ConsensusHome.jsx
  src/routes/main/MainFooter.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
  src/routes/main/ModalStyle.css
  src/routes/main/TabAboutUs.jsx
  src/routes/main/TabContact.jsx
  src/routes/main/TabHome.jsx
  src/routes/main/TabService.jsx
Labels: feat

#35 [FEAT] 벨류에이션 생성시 종목과 템플릿에 해당하는 3개년 데이터를 엑셀로 가져오기 #23
  package-lock.json
  package.json
  src/apis/template.js
  src/apis/valuation.js
  src/components/consensus/valuation/Excel.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
  src/constants/valuation.js
  src/routes/valuationCreateExcel/page.jsx
  vite.config.js
Labels: feat

#38 [REFACTOR] 개별 컨센서스 페이지에서 컨센서스 비율, 종가 차트 UI 수정
  src/components/consensus/home/GraphDemo.jsx
  src/components/consensus/home/detail/ChartConsensus.jsx
  src/components/consensus/home/detail/ChartStock.jsx
  tailwind.config.js
Labels: refactor

#41 [FEAT] excel 라이브러리 변경, css 수정, 컴포넌트화하여 리팩터링 #40
  package-lock.json
  package.json
  src/components/consensus/valuation/ExcelHeader.jsx
  src/routes/consensus/page.jsx
  src/routes/valuationCreateExcel/page.jsx
  src/routes/valuationCreateExcel/page.jsx.back
  src/routes/valuationCreateExcel/valuationCreateExcel.css
Labels: fix

#48 [FIX] merge conflict 해결 #47
  src/components/consensus/myPage/Valuation.jsx
  src/routers/main-router.jsx
  src/routes/main/TabHome.jsx
  tailwind.config.js
Labels: fix

#49 [FEAT] : 로그인/회원가입 기능 추가
  src/apis/consensus.js
  src/apis/template.js
  src/apis/user.js
  src/apis/valuation.js
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/GraphDemo.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
  src/utiles/setupProxy.jsx
  vite.config.js
Labels: feat

#53 [FEAT] TemplateFooter 추가
  src/components/consensus/valuation/TemplateFooter.jsx
  src/routes/templateEditExcel/page.jsx
Labels: feat

#55 [FEAT] 변경된 엑셀 라이브러리로 3개년 데이터 불러와 템플릿에 맞게 엑셀 데이터에 삽입하는 기능 구현 #37
  src/apis/template.js
  src/apis/valuation.js
  src/components/consensus/myPage/Template.jsx
  src/components/consensus/valuation/ExcelHeader.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
  src/routes/valuationCreateExcel/page.jsx
  vite.config.js
Labels: feat, fix

#56 [REFACTOR]: Template API 리팩토링 #52
  src/apis/template.js
  src/components/consensus/myPage/Template.jsx
  src/routes/templateEditExcel/page.jsx
Labels: refactor

#58 [FEAT] 템플릿화 시 모달로 템플릿명 입력받기 #57
  src/components/consensus/valuation/ExcelHeader.jsx
  src/routes/valuationCreateExcel/page.jsx
Labels: feat

#62 [FIX] 템플릿 선택 드롭다운에 API 연결하고 CSS 수정 #59
  src/apis/template.js
  src/components/consensus/valuation/ExcelHeader.jsx
  src/components/consensus/valuation/InputTemplate.jsx
Labels: feat

#65 [FEAT] 돋보기 삭제 및 화살표 색상 추가 #61
  package-lock.json
  package.json
  src/apis/valuation.js
  src/components/NavBar.jsx
  src/components/consensus/home/ArrowStyle.css
  src/components/consensus/home/StockList.jsx
  src/routes/valuationEditExcel/page.jsx
Labels: chore, fix

#69 [FEAT] 벨류에이션 생성 화면에서 종목 선택 할 때 검색 API 연결하기 #63
  index.html
  package-lock.json
  package.json
  src/apis/search.js
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
  src/main.jsx
Labels: feat

#74 [FEAT] 컨센선스 화면에 검색바 기능 구현 #71
  src/apis/consensus.js
  src/components/consensus/home/ConsensusList.jsx
  src/components/consensus/home/Search.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/valuation/InputStock.jsx
Labels: feat

#73 [FEAT] 현재가 데이터 요청에 추가 #72
  src/routes/valuationCreateExcel/page.jsx
Labels: feat

#75 [FIX] main화면의 css 수정 #70
  src/routes/main/MainFooter.jsx
  src/routes/main/TabAboutUs.jsx
  src/routes/main/TabContact.jsx
  src/routes/main/TabHome.jsx
  src/routes/main/TabService.jsx
  src/routes/main/page.jsx
  tailwind.config.js
Labels: fix

#77 [REFACTOR] 전체/개별 컨센서스 기능 수정
  public/assets/gif/gif_valuega_demo.gif
  src/components/NavBar.jsx
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/ConsensusList.jsx
  src/components/consensus/home/GraphDemo.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/home/detail/ChartConsensus.jsx
  src/components/consensus/home/detail/ChartStock.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/components/consensus/home/detail/StockPredictionList.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
  src/routes/main/TabAboutUs.jsx
  src/routes/main/page.jsx
  vite.config.js
Labels: refactor

#78 [FIX] 템플릿화 할 때 user_id 가져오기#76
  src/components/NavBar.jsx
  src/components/consensus/home/Search.jsx
  src/components/consensus/valuation/ExcelEditHeader.jsx
  src/components/consensus/valuation/ExcelHeader.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/TemplateHeader.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
Labels: fix

#80 [FEAT] valuation 저장 후 페이지 전환 추가
  src/routes/valuationCreateExcel/page.jsx
Labels: feat

#81 feat: 템플릿 생성시 페이지 전환
  src/components/consensus/valuation/ExcelHeader.jsx
  src/routes/main/page.jsx
Labels: feat, fix

#82 [FEAT] DEVELOP 기능 MAIN 병합
  index.html
  package-lock.json
  package.json
  public/assets/gif/gif_valuega_demo.gif
  src/apis/consensus.js
  src/apis/search.js
  src/components/NavBar.jsx
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/ConsensusList.jsx
  src/components/consensus/home/GraphDemo.jsx
  src/components/consensus/home/Search.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/home/detail/ChartConsensus.jsx
  src/components/consensus/home/detail/ChartStock.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/components/consensus/home/detail/StockPredictionList.jsx
  src/components/consensus/valuation/ExcelEditHeader.jsx
  src/components/consensus/valuation/ExcelHeader.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/TemplateHeader.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
  src/main.jsx
  src/routes/main/MainFooter.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
  src/routes/main/TabAboutUs.jsx
  src/routes/main/TabContact.jsx
  src/routes/main/TabHome.jsx
  src/routes/main/TabService.jsx
  src/routes/main/page.jsx
  src/routes/valuationCreateExcel/page.jsx
  tailwind.config.js
  vite.config.js
Labels: feat

#85 [FEAT] 벨류에이션 생성 화면, 마이페이지 화면에서 인증되지 않은 사용자는 로그인하도록 수정 #83
  index.html
  public/valuega_favicon.svg
  src/components/NavBar.jsx
  src/components/consensus/myPage/MyPage.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
Labels: feat, fix

#86 [REFACTOR] 메인/전체/개별 페이지 버그 수정
  src/components/NavBar.jsx
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/ConsensusList.jsx
  src/components/consensus/home/Search.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/home/detail/ChartStock.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/components/consensus/home/detail/StockPredictionList.jsx
  src/routes/main/MainFooter.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
Labels: refactor

#88 Main 으로 배포
  index.html
  public/valuega_favicon.svg
  src/components/NavBar.jsx
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/ConsensusList.jsx
  src/components/consensus/home/Search.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/home/detail/ChartStock.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/components/consensus/home/detail/StockPredictionList.jsx
  src/components/consensus/myPage/MyPage.jsx
  src/components/consensus/valuation/InputStock.jsx
  src/components/consensus/valuation/InputTemplate.jsx
  src/components/consensus/valuation/ValuationCreate.jsx
  src/routes/main/MainFooter.jsx
  src/routes/main/MainHeader.jsx
  src/routes/main/MainModal.jsx
Labels: feat

#89 [REFACTOR] 개별 컨센서스 css 수정
  src/components/NavBar.jsx
  src/components/consensus/home/detail/ChartConsensus.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/components/consensus/home/detail/StockPredictionList.jsx
  src/components/consensus/myPage/Valuation.jsx
  src/routes/main/MainModal.jsx
Labels: refactor

#94 [REFACTOR] 컨센서스 에러 수정
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/routes/main/MainHeader.jsx
Labels: refactor

#95 Develop 기능 Main 병합
  src/components/consensus/home/ConsensusHome.jsx
  src/components/consensus/home/StockList.jsx
  src/components/consensus/home/detail/ConsensusDetail.jsx
  src/routes/main/MainHeader.jsx
Labels: feat, fix

#98 [REFACTOR] README 내용 수정
  README.md
Labels: docs
